### ISSUE TITLE
Support for XPlane11?

### ISSUE THREAD

**Issue by steve5031** [Colmanian/AuthentiKit-Trim-Calibration#17]
I was wondering if this will work with XPlane11? If not will there be support for it in the future. 

Thanks,
Steve

**Comment by Colmanian** [comment]
Hi Steve, 

The App doesn't interface with any particular simulator directly. All it does is drive vJoy. vJoy is the software that interfaces with the sim. For that reason the Authentikit app isn't incompatible with any particular sim if you see what I mean. If the sim supports vJoy then the app will work :)

As for whether X Plane 11 supports vJoy - I haven't tried that but it should do. vJoy just shows up as a real joystick to Windows. Since everything is free it would be worth giving it a try. I'd appreciate you letting me know how you get on if you do attempt this.

Many Thanks,

Ian
