### ISSUE TITLE
Virtual Output Axis blank

### ISSUE THREAD

**Issue by Papillonthe84** [Colmanian/AuthentiKit-Trim-Calibration#37]
It happens sometimes that when I start Authentikit, the "Virtual Output Axis" drop-down list is blank so that I cannot use my mapping.

I do not know what to do to restore it.

Any idea ?
Many thanks.

**Comment by Rafman72** [comment]
I am having the same issue

**Comment by Colmanian** [comment]
Yep this happens when vJoy crashes. The only way to get around this is to restart your PC unfortunately. Sorry about this. Hopefully vJoy will be updated to be more reliable (I don't control vJoy). Bugs like this one will cause vJoy to crash [Issue 30](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/issues/30), so as I fix these, you should see the crashes less frequently.

**Comment by Colmanian** [comment]
Update: Try running [vJoy 2.1.9](https://github.com/jshafer817/vJoy/releases/tag/v2.1.9.1) rather than 2.2. I find it's more reliable and doesn't crash as much (haven't seen it crash at all yet).
